
[build-system]
requires = ["scikit-build-core >=0.4.3", "nanobind >=2.13.0"]
build-backend = "scikit_build_core.build"

[project]
name = "beave"
description = "A very Canadian utility for genomic clustering and distance querying."
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Matthew Wells", email = "matthew.wells@phac-aspc.gc.ca" }]
classifiers = ["License :: Apache-2.0"]
dependencies = ["numpy >= 2.4.0", "polars >=1.41.1", "scipy >= 1.17.0"]
version = "0.0.6"

[project.scripts]
beave = "beave.__main__:async_main"

[project.optional-dependencies]
dev = [
  "pytest>=9.0.2",
  "scipy-stubs",
  "hypothesis>=6.0.0",
  "pytest-workflow>=2.0.1",
  "mypy>=1.19.1",
  "ruff>=0.15.7",
  "pytest-benchmark>=5.2.3",
]

[tool.scikit-build]
minimum-version = "0.8"
build-dir = "build/{wheel_tag}"
wheel.py-api = "cp312" # build wheels for stable API Cpython 3.12+
cmake.args = ["-DTARGET_GROUP=python"]
cmake.version = ">=3.26.1"
messages.after-success = "{green}Wheel successfully built"
messages.after-failure = """
{bold.red}Sorry{normal}, build failed. Your platform is {platform.platform}.
"""
logging.level = "DEBUG"


[tool.mypy]
exclude = ["^test", "src/beave/test\\.py$"]
files = ["src/beave/*.py"]
disallow_untyped_defs = true
disallow_incomplete_defs = true


[tool.complexipy]
paths = ["src/beave"]
max-complexity-allowed = 10


[tool.ruff]
line-length = 100
lint.select = [
  "E",
  "F",
  "TRY",
  "FLY",
  "I",
  "NPY",
  "N",
  "PERF",
  "W",
  "D",
  "PL",
  "PLE",
  "PLR",
  "PLW",
  "UP",
  "FURB",
  "RUF",
]

[tool.cibuildwheel]
build-verbosity = 1
archs = ["auto64"]


[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"
