"""Re-implementation of mcluster."""

from dataclasses import dataclass
from enum import Enum, StrEnum
from pathlib import Path

import numpy as np
import polars as pl
import scipy
from numpy import typing as npt

import dist_mat as dm
from dist_mat._internal.log import init_logger
from dist_mat._internal.transform_data import (
    prep_data,
    read_input_profiles,
    subset_columns,
    transform_data,
)

logger = init_logger(__name__)


class ValueLeavesError(Exception):
    """Exception for raising a value error for un-equal numbers of objects."""

    def __init__(self, n_leaves: int, n_objects: int) -> None:
        """ValueError for unequal numbers of leaves and sample names."""
        super().__init__(f"Expected {n_objects} leaf names, got {n_leaves}.")


class LinkageMetric(StrEnum):
    """Linkage options that can be passed to scipy."""

    SINGLE = "single"
    AVERAGE = "average"
    COMPLETE = "complete"


class BranchLengthType(StrEnum):
    """Branch length types used for converting tree branch metrics."""

    PATRISTIC = "patristic"
    COPHENETIC = "cophenetic"


@dataclass(slots=True)
class ClusterArguments:
    """CLI arguments for clustering program.

    Disabling the pylint warning for too-many-instance-attributes
    as the number of attributes seems appropriate here for the purpose
    the class serves.
    """

    # pylint: disable=too-many-instance-attributes

    input_file: Path
    delimiter: str
    thresholds: list[float]
    method: str
    cores: int
    columns_path: Path | None
    count_missing: bool
    scaled: bool
    tree_output: Path
    cluster_outputs: Path
    branch_length_type: BranchLengthType
    filter_threshold: float


class LinkageMatrixFields(Enum):
    """From the scipy docs.

    A by 4 matrix Z is returned. At the i-th iteration, clusters with indices
    Z[i, 0] and Z[i, 1] are combined to form cluster n+1. A cluster with an
    index less than n corresponds to one of the original observations. The
    distance between clusters Z[i, 0] and Z[i, 1] is given by Z[i, 2].
    The fourth value Z[i, 3] represents the number of original observations in
    the newly formed cluster.

    """

    OBS1 = 0  # Observation 1, can be a sample or formed cluster
    OBS2 = 1  # Observation 2, this is a sample or cluster that is being combined wit OBS 1
    DISTANCE = 2  # This is the distance between OBS1 and OBS2
    NUM_OBSERVATIONS = (
        3  # This value represents the number of orignal observations in the new cluster
    )


def linkage_matrix_to_nwk(linkage_matrix: npt.NDArray, sample_ids: list[str]) -> str:
    """Code is taken from an old Scipy PR.

    I did not come up with this code below is has been adapated from a scipy PR here:
    https://github.com/scipy/scipy/pull/17329/changes

    The inputs are the linkage matrix from scipy, and the sample_ids correspond to
    the alleleic profiles.
    """
    n_objects: int = linkage_matrix.shape[0] + 1
    n_leaves: int = len(sample_ids)
    if n_objects != n_leaves:
        raise ValueLeavesError(n_leaves, n_objects)

    newick_intermediates: list[str | None] = sample_ids + [None] * linkage_matrix.shape[0]
    cluster_dists: list[np.float64] = [np.float64(0)] * (n_objects + linkage_matrix.shape[0])
    for i, row in enumerate(linkage_matrix):
        dist: np.float64 = row[LinkageMatrixFields.DISTANCE.value]
        fi: int = int(row[LinkageMatrixFields.OBS1.value])
        fj: int = int(row[LinkageMatrixFields.OBS2.value])
        cdi: np.float64 = dist - cluster_dists[fi]
        cdj: np.float64 = dist - cluster_dists[fj]
        newick_subtree: str = f"({newick_intermediates[fi]}:{cdi},{newick_intermediates[fj]}:{cdj})"
        newick_intermediates[i + n_objects] = newick_subtree
        cluster_dists[i + n_objects] = dist
        newick_intermediates[fi] = None
        newick_intermediates[fj] = None

    return newick_intermediates[linkage_matrix.shape[0] - 1 + n_objects] + ";"


def compute_dists(
    profiles: pl.DataFrame,
    count_missing: bool,
    scaled: bool,
    threads: int,
    filter_threshold: float = 1.0,
) -> npt.NDArray:
    """Compute the 1D array required by scipy for generation of the linkage matrix."""
    prepared_profiles = prep_data(profiles, filter_threshold, transform_data)
    logger.debug("Tranformed data for computation in C++ sub-routine.")
    distances = dm.calc_dists(prepared_profiles, threads, scaled, count_missing)
    logger.debug("Finished C++ sub-routine.")
    return distances


def compute_linkage_matrix(profiles_computed: npt.NDArray, linkage_method: str) -> npt.NDArray:
    """Use scipy to compute a linkage matrix from the calculated distances.

    profiles_computed refers to a 1D condensed array generated by calc_dists
    """
    linkage = scipy.cluster.hierarchy.linkage(profiles_computed, method=linkage_method)  # type: ignore[arg-type]
    logger.debug(f"Calculated {linkage_method} linkage.")
    return linkage


def assign_clusters(
    linkage: npt.NDArray, thresholds: list[int | float], labels: list[str]
) -> pl.DataFrame:
    """Generate the new cluster membership code for all samples at each threshold.

    Thresholds are assumed to be sorted in descending order e.g [10.0, 5.0, 1.0]
    """
    data_to_populate = [pl.Series(name="SampleID", values=labels)]
    cols_concat = []

    for threshold in thresholds:
        col_name = f"level_{threshold!s}"
        data_to_populate.append(
            pl.Series(
                name=col_name,
                values=scipy.cluster.hierarchy.fcluster(linkage, threshold, criterion="distance"),
                dtype=pl.UInt32,
            )
        )
        cols_concat.append(col_name)
        logger.debug(f"Calculated flat clusters for threshold: {threshold}")

    outputs = pl.DataFrame(data_to_populate, orient="col")
    outputs = outputs.with_columns(
        pl.concat_str(cols_concat, separator=".").alias("denovo_address")
    )

    return outputs


def convert_branch_lengths(
    linkage_matrix: npt.NDArray, branch_length_type: BranchLengthType
) -> npt.NDArray:
    """Convert linkage matrix to to cophenetic distance if needed."""
    if branch_length_type == BranchLengthType.PATRISTIC:
        for row in linkage_matrix:
            row[LinkageMatrixFields.DISTANCE.value] *= 0.5
            logger.info("Converted branc lengths to patristic distances.")
    return linkage_matrix


def cluster(cluster_args: ClusterArguments) -> None:
    """Runner function of cluster."""
    profiles = read_input_profiles(
        cluster_args.input_file,
        cluster_args.delimiter,
        cluster_args.cores,
    )
    logger.info("Loaded profiles")

    if cluster_args.columns_path:
        profiles = subset_columns(profiles, cluster_args.columns_path, None)
        logger.info("Subset columns.")

    distances = compute_dists(
        profiles,
        cluster_args.count_missing,
        cluster_args.scaled,
        cluster_args.cores,
        cluster_args.filter_threshold,
    )
    logger.info("Computed distances.")
    linkages = compute_linkage_matrix(distances, cluster_args.method)
    logger.info("Computed linkage matrix.")
    cluster_args.thresholds.sort(reverse=True)
    logger.info("Thresholds being used for generating linkages: %s", cluster_args.thresholds)

    sample_names = profiles.select(pl.nth(0)).to_series().to_list()
    # write out the tree
    cluster_memberships = assign_clusters(linkages, cluster_args.thresholds, sample_names)
    logger.info("Assigned clusters.")

    linkages = convert_branch_lengths(
        linkages, cluster_args.branch_length_type
    )  # convert branch lengths for tree display if needed
    newick = linkage_matrix_to_nwk(linkages, sample_names)

    with cluster_args.tree_output.open("w") as to:
        to.write(newick)
    logger.info("Wrote newick tree to: %s", str(cluster_args.tree_output))

    cluster_memberships.write_csv(
        cluster_args.cluster_outputs,
        separator=cluster_args.delimiter,
        include_header=True,
    )
    logger.info("Wrote cluster memberships to: %s", str(cluster_args.cluster_outputs))
