name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.x'

      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.14'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip'
      # You can test your matrix by printing the current Python version
      - name: Install dependencies
        run: python -m pip install --upgrade pip; pip install --no-build-isolation -ve .[dev]
      - name: Lint with mypy
        run: |
          mypy
      - name: Run pytest
        run: |
          pytest

  complexity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check Python Code Complexity
      uses: rohaquinlop/complexipy-action@v3
      with:
        paths: ${{ github.workspace }}/src/dist-mat/*.py  # Analyze the entire repository
        ignore_complexity: false 
        output_json: true
